### ISSUE TITLE
IB gateway still restarts after #18

### ISSUE THREAD

**Issue by qt1729** [QuantConnect/IBAutomater#19]
Hi guys, 

Yesterday I have tested the changes in the IBAutomater after you merged #18  I see the issues that prevent me from running IBGateway with IBAutomater - gateway restarts. The gateway application goes down on the scheduled logoff/restart time even despite IBAutomater trying to change the restart time in the dialog. 

Platform: Win 2012 (x64)
 
Steps to repro: 
1. Schedule the IB gateway for the time T+3 hours (it did not work for me if I set T+1 hours). 
2. Run IBAutomater. 
3. In three hours IB gateway goes down without recovery. 
I have tried to reproduce this behavior by manually starting IB gateway, scheduling restart for T+3 hours, and trying to keep it alive, but it just restarts. 

Any ideas on how to fix this? 

Wondering if it is possible to download prev versions of IB Gateway as a temporary solution for now?

Best regards,
Pavel

**Comment by StefanoRaggi** [comment]
Hi Pavel,
when using IBGateway v978, IBAutomater tries to prevent automatic logoff by moving the next logoff time to the following day.
Unfortunately, I noticed the behavior is not consistent: 
sometimes it works, sometimes it ignores the setting and will log off anyway (closing itself).

In LEAN we solved this problem handling the `Exited` event, restarting IBGateway and reconnecting:
https://github.com/QuantConnect/Lean/blob/master/Brokerages/InteractiveBrokers/InteractiveBrokersBrokerage.cs#L2995

If you are using LEAN, we recommend using our docker file to prevent versioning issues:
https://github.com/QuantConnect/Lean/blob/master/DockerfileLeanFoundation

If you need them, you can download the old IBGateway v974 versions from the QC CDN:
- http://cdn.quantconnect.com/interactive/ibgateway-latest-standalone-linux-x64-v974.4g.sh
- http://cdn.quantconnect.com/interactive/ibgateway-latest-standalone-windows-x64-v974.4g.exe

**Comment by qt1729** [comment]
Hi Stefano, 

Thank you for your reply. I have tested it today - indeed checking on OnIbAutomaterExited() worked perfectly well. It seems like it is safe now to remove this logoff time moving logic. Otherwise, it is going to drift significantly in the long run.
