### ISSUE TITLE
Settings will not be downloaded from the server because the feature has been temporarily disabled. Displayed

### ISSUE THREAD

**Issue by ceasar09** [QuantConnect/IBAutomater#22]
Running demo project, and "Settings will not be downloaded from the server because the feature has been temporarily disabled. " msg displayed, login hangs on.
Does this has any problems with my config or my account?
I've tried IBController, this does work.
ibgateway 977，windows 10

**Comment by ceasar09** [comment]
![image](https://user-images.githubusercontent.com/8676326/91143298-dcd37900-e6e4-11ea-88cd-7694662f1f9d.png)

**Comment by ceasar09** [comment]
974 tried， also the same message displayed.

**Comment by ceasar09** [comment]
java SDK problem,  change to java jre,  seems to be ok.

**Comment by EswarKakani** [comment]
I ran into this issue with 981, but different message displayed "invalid twsinfo"
