### ISSUE TITLE
Trading Mode toggle button not found

### ISSUE THREAD

**Issue by theplayerseven** [QuantConnect/IBAutomater#33]
Hi,

I am running into the issue that it seems the automator cannot locate the switch for trading mode. The log is shown as following. Does anyone have similar experience before?

Thanks,
R

StartIBGateway(): starting IBGateway
StartIBGateway(): IBGateway started
Window event: [WINDOW_ACTIVATED] - Window title: [IB Gateway]
Window event: [WINDOW_OPENED] - Window title: [IB Gateway]
Error: java.lang.Exception: Trading Mode toggle button not found

**Comment by Martin-Molinero** [comment]
Sorry for the late response, it's hard to know without more information but it sounds like it's due to the gateway version.
Closing issue for now, please retest with latest version of the automater & gateway 10.23
