### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by ReDev1L** [QuantConnect/IBAutomater#4]
Hello.
Thanks for awesome tool. I've looked into sources, and i understood that its a java program wrapper. I dont know C# and Java tools, and looking to do docker image for that wrapper.I need to know how to build this wrapper to work in docker image in headless mode, if thats possible.
Can you help me?

**Comment by jaredbroad** [comment]
Great idea. Let us review this for you and we can ship a simple docker image which handles the heavy lifting for you. 

Just a note this a "feature" not a "bug" so we'll have to address all the bugs in the package first then move onto this implementation.

**Comment by patrickhop** [comment]
this would be really nice to have.

**Comment by JohnShiuMK** [comment]
Hi jaredboard, could you ship me the simple docker image too, please?

**Comment by mrpeterlee** [comment]
Love to see this thread delivered...
