### ISSUE TITLE
Support automating automatic logoff in >974 IB Gateway

### ISSUE THREAD

**Issue by imphasing** [QuantConnect/IBAutomater#6]
After version 974 of IB Gateway, IB re-introduced the automatic logoff every day thing that has plagued IB automation with TWS for ages.. now in IB Gateway latest (976 at this time) - It would be great if IBAutomater could support logging in again when this popup appears.

**Comment by StefanoRaggi** [comment]
Assuming you mean this popup:
![image](https://user-images.githubusercontent.com/7236689/60748705-fec5e580-9f90-11e9-9a64-de75dabf396b.png)
we just merged an update to support re-login properly, which has been tested with IBGateway v974 (default version used in LEAN and QC cloud).

Please let us know if this update also resolved your issue with 976.

**Comment by imphasing** [comment]
![Photo Jul 05, 7 57 46 PM](https://user-images.githubusercontent.com/81447/60750623-d1ad0f00-9f5f-11e9-9006-f047cf72470a.jpg)

not that dialog - in 976 onward ib introduced the daily logoff nag just like they have in tws if you‘ve ever dealt with that. ib gateway now logs you out every day at a time of your choice - would be awesome to automate that.

**Comment by imphasing** [comment]
I did some more research on this tonight - when you have ib gateway automatically restart instead of automatically log off, there is no login dialog for you to automate - it logs back in for you. However the default is to automatically log off (unlike my screenshot, IBAutomater appears to use a blank default profile perhaps so the settings are fresh each time?) which means the gateway just exits with no prompts at your specified time..

I think what needs to be automated for current latest version is:

1. Select automatically restart, leave the default time of 11:45 pm set but change the radio button to “Auto restart”
2. Have LEAN be able to handle a gateway restart event and maintain broker connection - I have not tested this as I can’t get the restart functionality to work while LEAN is running - perhaps it can already handle this?

Since this option appears only in 976 it will probably need to be some version specific behavior - that configuration option doesn’t even exist in 974 I believe.

If I could get IBAutomater to start with the “Auto restart” option I can test how LEAN coexists with this configuration option, maybe it can tolerate a restart already.

**Comment by imphasing** [comment]
Here is the ib doc page it wants me to read when I select “Auto restart” btw: https://www.interactivebrokers.com/en/software/tws/twsguide.htm#usersguidebook/configuretws/auto_restart_info.htm

Note that you can’t disable this it seems - you either get automatically logged out or you can choose to restart in the latest versions of ib gateway

Seems it will prompt for auth once a week as well, further adding to the complexity of this.

My workaround for this issue is I have a script to terminate LEAN and ib gateway every day after my configured restart time then start it back up again - this reauths me and appears to work fine but this will surely be an issue for 24 hour markets..
