### ISSUE TITLE
Configurable Sunday Restart

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/IBAutomater#70]
IBAutomater is set to try to connect to IB Gateway as early as Sunday 2 AM EST: [IBAutomater.cs#L769](https://github.com/QuantConnect/IBAutomater/blob/master/QuantConnect.IBAutomater/IBAutomater.cs#L769)
Some users are not awake by that time and will miss the 2FA request.

This restart could be configurable to attend to the user's timezone.

**Comment by jhonabreul** [comment]
Closing with PR from IB Brokerage: https://github.com/QuantConnect/Lean.Brokerages.InteractiveBrokers/pull/41
